name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:

  check:
    needs: []
    runs-on: ubuntu-20.04
    steps:
      - name: "Set up GitHub Actions"
        uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: "Install Prettier"
        run: npm install --global prettier@2.3.0
      - name: "Check code format"
        run: make check

  test:
    needs: [check]
    runs-on: ubuntu-20.04
    steps:
      - name: "Set up GitHub Actions"
        uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: "Install dependencies"
        run: npm install-clean
      - name: "Run tests"
        run: make test

  build:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - name: "Set up GitHub Actions"
        uses: actions/checkout@v2
      - name: "Build Docker image"
        run: make docker-build
