name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  check:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: "Set up GitHub Actions"
        uses: actions/checkout@v2
      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: "Install dev dependencies"
        run: npm install --silent --only=dev
      - name: "Check code format"
        run: make check

  build:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: "Set up GitHub Actions"
        uses: actions/checkout@v2
      - name: "Build Docker image"
        run: make docker-build
